#ifndef __GAME_CONFIG_H__
#define __GAME_CONFIG_H__

#define GAME_ENDED_SUCCESS 0
#define GAME_ERROR_INIT_FAILED -1
#define GAME_ERROR_NO_DEMO_SELECTED -2
#define GAME_ERROR_DEMO_NOT_FOUND -3

#endif // __GAME_CONFIG_H__